// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import './globals.css'; // Next.js's default global CSS with Tailwind directives
import Navbar from './component/Navbar'; // Adjust path if your components folder is elsewhere
    import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cao Legal Solutions',
  description: 'At Cao Legal Solutions, we offer expert legal services in family law, employment law, property conveyancing and migration law. Led by a principal lawyer from a migrant background, we bring a broader understanding of cultural diversity and lived experience to every matter we handle.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Cao Legal Solutions</title>
        <meta name="description" content="At Cao Legal Solutions, we offer expert legal services in family law, employment law, property conveyancing and migration law. Led by a principal lawyer from a migrant background, we bring a broader understanding of cultural diversity and lived experience to every matter we handle." />
        {/* Open Graph for social sharing */}
        <meta property="og:title" content="Cao Legal Solutions" />
        <meta property="og:description" content="At Cao Legal Solutions, we offer expert legal services in family law, employment law, property conveyancing and migration law. Led by a principal lawyer from a migrant background, we bring a broader understanding of cultural diversity and lived experience to every matter we handle." />
        <meta property="og:image" content="/svh.svg" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.caolegal.com.au/" />
        {/* Twitter Card for social sharing */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Cao Legal Solutions" />
        <meta name="twitter:description" content="At Cao Legal Solutions, we offer expert legal services in family law, employment law, property conveyancing and migration law. Led by a principal lawyer from a migrant background, we bring a broader understanding of cultural diversity and lived experience to every matter we handle." />
        <meta name="twitter:image" content="/svh.svg" />
        {/* Canonical tag for homepage */}
        <link rel="canonical" href="https://www.caolegal.com.au/" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="apple-touch-icon" href="/svh.svg" />
      </head>
      <body className={`${inter.className} min-h-screen bg-slate-50 text-slate-800 flex flex-col`}>
        <Navbar />
        <main className="pt-10 flex-grow">
          {children}
        </main>
        <footer className="mt-20 py-8 text-center text-sm text-slate-500 bg-slate-100 text-slate-500 border-t border-slate-200">
          Liability limited by a scheme approved under Professional Standards Legislation
        </footer>
      </body>
    </html>
  );
}
