// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
    import './globals.css'; // Next.js's default global CSS with Tailwind directives
    import Navbar from './component/Navbar'; // Adjust path if your components folder is elsewhere
    import { Inter } from 'next/font/google';

    const inter = Inter({ subsets: ['latin'] });

    export const metadata = {
      title: 'Sterling & Associates Law Firm',
      description: 'Expert legal services for corporate, family, criminal, real estate, IP, and litigation needs.',
    };

    export default function RootLayout({
      children,
    }: {
      children: React.ReactNode;
    }) {
      return (
        <html lang="en">
          <body className={`${inter.className} min-h-screen bg-slate-50 text-slate-800`}>
            {/* Navbar is rendered globally here */}
            <Navbar />
            {/* Main content area, padding-top to offset fixed navbar height (h-16 -> 4rem). */}
            <main className="pt-20">
              {children} {/* This is where your page.tsx content will be rendered */}
            </main>
            {/* Footer is rendered globally here */}
            <footer className="mt-20 py-8 text-center text-sm text-slate-500 bg-slate-100 text-slate-500 border-t border-slate-200">
              © {new Date().getFullYear()} Sterling & Associates
            </footer>
          </body>
        </html>
      );
    }
    